// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///    options: DefaultFirebaseOptions.currentPlatform,
///  );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPAISqculdn0kFdD03WFDyoNKVlUtA_hA',
    appId: '1:630325032808:web:fc8a058f8a3a0b24bf88dd',
    messagingSenderId: '630325032808',
    projectId: 'calender-a5c3e',
    authDomain: 'calender-a5c3e.firebaseapp.com',
    storageBucket: 'calender-a5c3e.appspot.com',
    measurementId: 'G-X3KVTKCHG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPVjSUEmRaCik0u4rMlggj-SczdraDqzM',
    appId: '1:630325032808:android:1b38b4282635757cbf88dd',
    messagingSenderId: '630325032808',
    projectId: 'calender-a5c3e',
    storageBucket: 'calender-a5c3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-GTQoaT2egc_r3QKH8c153VGJePPKrGw',
    appId: '1:630325032808:ios:ee449393c051e8e5bf88dd',
    messagingSenderId: '630325032808',
    projectId: 'calender-a5c3e',
    storageBucket: 'calender-a5c3e.appspot.com',
    iosClientId: '630325032808-oq982rglhlu7g7ajki2999qh7td1rqob.apps.googleusercontent.com',
    iosBundleId: 'com.example.calender',
  );

}

